local-service	= net

no-resolv
no-hosts

local-ttl	= 300

auth-server	= printclave.net,eth-lan
interface-name  = box.printclave.net,eth-lan
interface-name  = spoolman.printclave.net,eth-lan
interface-name  = apt.printclave.net,eth-lan
interface-name  = git.printclave.net,eth-lan
interface-name  = py.printclave.net,eth-lan
auth-zone 	= printclave.net
auth-soa	= 1,box.printclave.net

synth-domain	= printclave.net,172.16.20.0,172.16.20.255,ip*
