dhcp-authoritative

dhcp-range	= set:printclave,172.16.20.10,172.16.20.199,255.255.255.0,1w

dhcp-generate-names

dhcp-option	= option:router
dhcp-option	= option:dns-server,0.0.0.0
dhcp-option	= option:domain-search,printclave.net
dhcp-option	= option:ntp-server,0.0.0.0
