#!/usr/bin/env bash 

script_dir="$(dirname "$0")"
whl_dir="$script_dir/dist/whls"
cache_dir="$script_dir/cache"

typeset -a pip_args
pip_args=( --wheel-dir "$whl_dir" )
pip_args+=( --cache-dir "$cache_dir" )

set -e -x
for req_file in sources/*-requirements.txt; do
	# We do these one at a time, because different projects might have conflicting items
	pip wheel "${pip_args[@]}"  -r "$req_file"
done
